### ISSUE TITLE
Internal system error communicating with Rapid API (Can not construct instance of int from String value 'VI': not a valid Integer value)

### ISSUE THREAD

**Issue by haresh14** [eWAYPayment/eway-rapid-java#14]
Hello,
Card Type has been chagned from `Integer` to `String` in eway rapid API and because of that when we gets the successfull response and it tries to parse the data and if response contains the card type then it gives parse error as follow:

```Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of int from String value 'VI': not a valid Integer value
 at [Source: (BufferedInputStream); line: 1, column: 261] (through reference chain: com.eway.payment.rapid.sdk.entities.TransactionSearchResponse["Transactions"]->Object[][0]->com.eway.payment.rapid.sdk.beans.internal.Transaction["Customer"]->com.eway.payment.rapid.sdk.beans.internal.Customer["CardDetails"]->com.eway.payment.rapid.sdk.beans.external.CardDetails["CardType"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:55)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:907)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:443)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:309)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:287)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:156)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:17)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1470)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:912)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:808)
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:634)
```

The simple fix of this issue is to change the card type to string in `com.eway.payment.rapid.sdk.beans.external.CardDetails`. Can you please fix this?

Reference: https://eway.io/api-v3/#settlement-search

**Comment by chrisjowen** [comment]
Mental that this is still an open issue, its. a 30 second fix not even worth raising a PR for.
